import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..'),out=resolve(root,'qa'),review=resolve(root,'.impeccable/review');
await mkdir(out,{recursive:true});await mkdir(review,{recursive:true});
const browser=await chromium.connectOverCDP('http://127.0.0.1:9222');
const context=await browser.newContext({locale:'en-BD'});const page=await context.newPage();
const checks=[];let order;const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const check=async(name,fn)=>{await fn();checks.push({name,passed:true});console.log('PASS '+name);};
try{
 await page.goto('chrome://version');const profile=await page.locator('#profile_path').textContent();assert.match(profile.replaceAll('\\','/'),/^D:\/MCP\/chrome-real-profile\//i);
 await check('authorized profile and owned test tab',async()=>assert.ok(profile));
 await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:5188/?qa=1');await page.waitForFunction(()=>window.__SHOP__?.products.length===6&&window.__SHOP__.garage?.ready,{timeout:30000});await page.evaluate(()=>document.fonts.ready);
 await check('production identity and six real API catalog entries',async()=>{assert.match(await page.title(),/Diecast Dhaka/);assert.equal(await page.locator('.product-card').count(),6);assert.equal((await page.evaluate(()=>window.__SHOP__.products)).length,6);});
 await check('3D renderer contains chosen product and four wheels',async()=>{const s=await page.evaluate(()=>({id:window.__SHOP__.garage.getCar().name,wheels:window.__SHOP__.garage.getCar().userData.wheels.length,calls:window.__SHOP__.garage.renderer.info.render.calls}));assert.equal(s.id,'skyline');assert.equal(s.wheels,4);assert.ok(s.calls>30);});
 await page.screenshot({path:resolve(review,'desktop.png'),fullPage:true});await page.screenshot({path:resolve(out,'desktop-hero.png')});
 await check('desktop has no horizontal document overflow',async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false));
 const before=await page.evaluate(()=>window.__SHOP__.garage.getCar().rotation.y);await page.locator('#rotate-car').click();await page.waitForFunction(value=>Math.abs(window.__SHOP__.garage.getCar().rotation.y-value)>.2,before);
 await check('rotate button changes actual 3D mesh transform',async()=>assert.ok(Math.abs(await page.evaluate(()=>window.__SHOP__.garage.getCar().rotation.y)-before)>.2));
 await page.locator('[data-category="European"]').click();await check('category filter targets European casting',async()=>{assert.equal(await page.locator('.product-card').count(),1);assert.match(await page.locator('.product-name').textContent(),/Porsche/);});
 await page.locator('[data-action="clear-filters"]').first().click();await page.locator('#search').fill('Civic');await check('search resolves the actual casting',async()=>{assert.equal(await page.locator('.product-card').count(),1);assert.match(await page.locator('.product-name').textContent(),/Civic/);});await page.locator('#search').fill('');
 await page.locator('#sort').selectOption('high');await check('price sort follows server calculated prices',async()=>{const vals=await page.locator('.product-card').evaluateAll(nodes=>nodes.map(n=>window.__SHOP__.products.find(p=>p.id===n.dataset.product).price));assert.deepEqual(vals,[...vals].sort((a,b)=>b-a));});
 await page.locator('[data-action="save"][data-id="supra"]').click();await page.locator('[data-action="wishlist-filter"]').click();await check('saved cars filter persists product identity',async()=>{assert.equal(await page.locator('.product-card').count(),1);assert.equal(await page.locator('.product-card').getAttribute('data-product'),'supra');});await page.locator('[data-action="clear-filters"]').first().click();
 await page.locator('[data-action="detail"][data-id="porsche"]').first().click();await page.waitForFunction(()=>document.querySelector('#detail-canvas')?.dataset.product==='porsche');await page.screenshot({path:resolve(out,'product-detail.png')});
 await check('product inspection opens correct casting and 3D model',async()=>{assert.match(await page.locator('#detail-name').textContent(),/Porsche/);assert.equal(await page.locator('#detail-canvas').getAttribute('data-product'),'porsche');});
 await page.locator('#product-dialog [data-action="add"]').click();await page.waitForFunction(()=>window.__SHOP__.animation.history.at(-1)?.progress>.12&&window.__SHOP__.animation.history.at(-1)?.progress<.9);await page.screenshot({path:resolve(out,'car-to-cart.png')});await page.waitForFunction(()=>window.__SHOP__.animation.history.at(-1)?.completed,{timeout:20000});
 await check('selected Porsche drives through intermediate frames into cart',async()=>{const state=await page.evaluate(()=>({record:window.__SHOP__.animation.history.at(-1),quantity:window.__SHOP__.cart.porsche,canvasId:document.querySelector('#drive-canvas').dataset.product,canvasColor:document.querySelector('#drive-canvas').dataset.color}));assert.equal(state.record.id,'porsche');assert.equal(state.canvasId,'porsche');assert.equal(state.canvasColor,'#e86527');assert.ok(state.record.frames>=2);assert.ok(state.quantity>=1);assert.equal(state.record.completed,true);});
 await page.reload();await page.waitForFunction(()=>window.__SHOP__?.garage?.ready);await check('cart survives page reload',async()=>assert.ok((await page.evaluate(()=>window.__SHOP__.cart)).porsche>=1));
 await page.locator('#cart-toggle').click();await page.locator('[data-action="checkout"]').click();await page.locator('#checkout-form [name="name"]').fill('QA Demo Collector');await page.locator('#checkout-form [name="phone"]').fill('01700000000');await page.locator('#checkout-form [name="address"]').fill('QA fixture, Dhaka — not a real delivery');await page.locator('#checkout-form [value="outside"]').check();
 await check('checkout calculates selected Bangladesh delivery zone',async()=>{const o=await page.evaluate(()=>({display:document.querySelector('#checkout-total').textContent,subtotal:window.__SHOP__.products.reduce((s,p)=>s+p.price*(window.__SHOP__.cart[p.id]||0),0)}));assert.ok(o.display.includes((o.subtotal+150).toLocaleString('en-BD')));});
 // Non-idempotent: exactly ONE submission. Never automatically retry.
 await page.locator('#place-order').click();await page.waitForFunction(()=>window.__SHOP__.lastOrder!==null,{timeout:15000});order=await page.evaluate(()=>window.__SHOP__.lastOrder);await page.screenshot({path:resolve(out,'order-confirmation.png')});
 await check('checkout saves a server order and empties cart',async()=>{assert.match(order.id,/^DD-/);assert.equal(order.status,'placed');assert.equal(order.deliveryFee,150);assert.equal(order.total,order.subtotal+150);assert.deepEqual(await page.evaluate(()=>window.__SHOP__.cart),{});});
 const response=await page.request.post('http://127.0.0.1:5188/api/orders/lookup',{data:{id:order.id,phone:'01700000000'}});const persisted=await response.json();
 await check('independent exact order readback matches submitted cars and total',async()=>{assert.equal(response.status(),200);assert.deepEqual(persisted.order.items,order.items);assert.equal(persisted.order.total,order.total);});
 await page.locator('#cart-dialog [data-action="close-dialog"]').click();await page.locator('nav [data-action="track"]').click();await page.locator('#tracking-form [name="id"]').fill(order.id);await page.locator('#tracking-form [name="phone"]').fill('01700000000');await page.locator('#tracking-form button[type="submit"]').click();await page.locator('.tracking-card').waitFor();
 await check('customer tracking form resolves persisted order',async()=>{assert.match(await page.locator('.tracking-card').textContent(),new RegExp(order.id));assert.match(await page.locator('.status-pill').textContent(),/placed/);});await page.locator('#info-dialog [data-action="close-dialog"]').click();
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('[data-action="add"][data-id="civic"]').click();await page.waitForFunction(()=>window.__SHOP__.cart.civic===1);
 await check('reduced motion skips driving but adds the right car',async()=>{const state=await page.evaluate(()=>window.__SHOP__.animation.history.at(-1));assert.equal(state.id,'civic');assert.equal(state.reduced,true);assert.equal(state.frames,0);assert.equal(state.completed,true);});await page.emulateMedia({reducedMotion:'no-preference'});
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('visible'));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:resolve(review,'mobile.png'),fullPage:true});await page.screenshot({path:resolve(out,'mobile-hero.png')});
 await check('390px mobile layout retains catalog without document overflow',async()=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.product-card').count(),6);assert.ok(await page.locator('#cart-toggle').isVisible());});
 await page.locator('#cart-toggle').click();await check('mobile cart remains operable in viewport',async()=>{const bounds=await page.locator('#cart-dialog').boundingBox();assert.ok(bounds.width<=390);assert.ok(await page.locator('[data-action="checkout"]').isVisible());});await page.keyboard.press('Escape');assert.equal(await page.locator('#cart-dialog').getAttribute('open'),null);
 await page.goto('http://127.0.0.1:5188/admin');await page.locator('#admin-login').waitFor();const denied=await page.request.get('http://127.0.0.1:5188/api/admin/products');
 await check('owner workbench exists and private API is locked by default',async()=>{assert.equal(denied.status(),503);assert.ok(await page.locator('#admin-login input[type="password"]').isVisible());});
 await check('no uncaught browser runtime errors across tested flows',async()=>assert.deepEqual(errors,[]));
 await page.goto('http://127.0.0.1:5188/');await page.setViewportSize({width:1440,height:900});await page.waitForFunction(()=>window.__SHOP__?.garage?.ready);await page.evaluate(()=>scrollTo(0,0));
 const report={passed:checks.every(c=>c.passed===true),count:checks.length,checks,orderId:order.id,orderTotal:order.total,profile,errors,screenshots:{desktop:resolve(review,'desktop.png'),mobile:resolve(review,'mobile.png'),animation:resolve(out,'car-to-cart.png')}};
 await writeFile(resolve(out,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,count:report.count,orderId:order.id,orderTotal:order.total,errors}));
}catch(e){await writeFile(resolve(out,'browser-failure.json'),JSON.stringify({passed:false,checks,error:e.stack,orderId:order?.id},null,2));console.error(e);process.exitCode=1;}
await context.close(); // This isolated QA context only, never the user's context.
// End only this test client's CDP connection. Never close the shared browser.
process.exit(process.exitCode||0);
