export function startAdmin({api,money,escape,refreshIcons}){
 const root=document.querySelector('#admin-app');let key='',products=[],orders=[],tab='inventory',editing=null;
 const icon=n=>`<i data-lucide="${n}"></i>`;
 const costs=['landedCost','packaging','overhead','returnReserve','shippingSubsidy','paymentFeeRate','targetMargin'];
 const labels={landedCost:'Landed acquisition cost (BDT)',packaging:'Packaging per car (BDT)',overhead:'Allocated overhead per car (BDT)',returnReserve:'Returns / damage reserve (BDT)',shippingSubsidy:'Seller-funded shipping (BDT)',paymentFeeRate:'Payment fee (%)',targetMargin:'Target net margin (%)',stock:'Available units'};
 async function request(path,options={}){return api('/api/admin'+path,{...options,headers:{'X-Admin-Key':key,...options.headers}});}
 function shell(){root.innerHTML=`<header class="admin-header"><h1>THE OWNER’S WORKBENCH.</h1><a href="/">Back to the collector garage ${icon('arrow-up-right')}</a></header><main class="admin-main"><div class="admin-intro"><h2>RUN THE GARAGE.</h2><p>Manage local order records, inventory and your 30% target net margin. Private costs stay on the server. This storefront is a demo until real SKUs, stock, photographs, business details and fulfillment are configured.</p></div><div id="admin-content"></div><p id="admin-error" class="form-error" role="alert" hidden></p></main>`;refreshIcons();}
 function error(message){const box=root.querySelector('#admin-error');box.textContent=message;box.hidden=false;}
 function login(){shell();root.querySelector('#admin-content').innerHTML=`<form id="admin-login" class="admin-login"><label>Local owner key<input name="key" type="password" autocomplete="off" required placeholder="The ADMIN_KEY from your local .env"></label><p class="admin-note">Not configured? Copy .env.example to .env, set a long owner key and restart the server. The key is kept only in this tab’s memory—not in localStorage.</p><button class="button primary" type="submit">Unlock workbench ${icon('arrow-right')}</button></form>`;refreshIcons();root.querySelector('#admin-login').addEventListener('submit',async e=>{e.preventDefault();key=new FormData(e.target).get('key');const b=e.target.querySelector('button');b.disabled=true;try{await load();}catch(err){key='';error(err.message);b.disabled=false;}});}
 async function load(){const [p,o]=await Promise.all([request('/products'),request('/orders')]);products=p.products;orders=o.orders;render();}
 function render(){shell();const active=orders.filter(o=>o.status!=='cancelled');const sales=active.reduce((s,o)=>s+(o.subtotal??o.total-o.deliveryFee),0);root.querySelector('#admin-content').innerHTML=`<div class="admin-metrics"><div><strong>${orders.length}</strong><span>Local order records</span></div><div><strong>${money(sales)}</strong><span>Non-cancelled merchandise order value · not collected revenue</span></div><div><strong>${products.reduce((s,p)=>s+p.stock,0)}</strong><span>Demo stock units</span></div></div><div class="admin-tabs"><button data-tab="inventory" class="${tab==='inventory'?'active':''}">Stock & margin</button><button data-tab="orders" class="${tab==='orders'?'active':''}">Order desk</button><button id="admin-refresh">Refresh</button><button id="admin-lock" class="admin-danger">Lock</button></div><div id="admin-tab-content"></div>`;
 if(tab==='inventory')inventory();else orderTable();refreshIcons();root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});root.querySelector('#admin-lock').onclick=()=>{key='';products=[];orders=[];login();};root.querySelector('#admin-refresh').onclick=()=>load().catch(e=>error(e.message));}
 function inventory(){const c=root.querySelector('#admin-tab-content');c.innerHTML=`<div class="admin-callout"><strong>30% margin is not 30% markup.</strong><br>Target selling price = all per-car costs ÷ (1 − net margin − payment fee rate), rounded UP to the next ৳10. Include shipping subsidies, tax/duties in landed cost and an honest overhead allocation. The target is not a profit guarantee; compare your calculated price with the real Bangladesh market before buying stock.</div><div id="cost-editor"></div><div class="table-scroll"><table><thead><tr><th>Casting</th><th>Landed cost</th><th>All unit costs</th><th>Selling price</th><th>Est. net margin</th><th>Stock</th><th>Action</th></tr></thead><tbody>${products.map(p=>{const cost=costs.slice(0,5).reduce((s,k)=>s+Number(p[k]||0),0);const net=p.price>0?(p.price*(1-(p.paymentFeeRate||0))-cost)/p.price:0;return `<tr><td>${escape(p.name)}<small>${escape(p.id)} · demonstration inventory</small></td><td>${money(p.landedCost)}</td><td>${money(cost)}</td><td><strong>${money(p.price)}</strong></td><td>${(net*100).toFixed(1)}%<small>Calculated, not realized</small></td><td>${p.stock}</td><td><button data-edit="${escape(p.id)}">Edit costs & stock</button></td></tr>`}).join('')}</tbody></table></div><p class="admin-note">Costs include landed cost, packaging, overhead allocation, returns reserve and seller-funded shipping. Delivery collected from the customer is passed through at cost; inaccuracies must be allocated as shipping subsidy.</p>`;c.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));}
 function editProduct(id){const p=products.find(p=>p.id===id);editing=id;const c=root.querySelector('#cost-editor');c.innerHTML=`<form class="cost-editor" id="cost-form"><h3>${escape(p.name)}</h3><div class="cost-grid">${[...costs,'stock'].map(k=>`<label>${labels[k]}<input type="number" name="${k}" required min="0" max="${k==='targetMargin'?'69.9':k==='paymentFeeRate'?'30':k==='stock'?'100000':'1000000'}" step="${k==='stock'?'1':'.01'}" value="${k.endsWith('Rate')||k==='targetMargin'?Number(p[k]||0)*100:Number(p[k]||0)}"></label>`).join('')}</div><div class="cost-preview"><div><span>Calculated selling price</span><strong id="cost-price">—</strong><small id="cost-margin"></small></div><div><button type="button" class="button secondary" id="cost-cancel">Cancel</button> <button type="submit" class="button primary">Save to inventory ${icon('check')}</button></div></div><p class="admin-note">Price is verified again on the server. Updating stock does not reorder from any supplier. Updating costs never changes previously placed orders.</p><p id="cost-error" class="form-error" role="alert" hidden></p></form>`;
 const form=c.querySelector('form');const values=()=>{const v=Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,Number(v)]));v.targetMargin/=100;v.paymentFeeRate/=100;return v;};
 const preview=()=>{const v=values();const base=costs.slice(0,5).reduce((s,k)=>s+v[k],0),den=1-v.targetMargin-v.paymentFeeRate;const price=den>0?Math.ceil((base/den)/10)*10:0;root.querySelector('#cost-price').textContent=price?money(price):'Check cost inputs';root.querySelector('#cost-margin').textContent=price?`${((price*(1-v.paymentFeeRate)-base)/price*100).toFixed(2)}% net margin after entered costs`:'';};form.oninput=preview;preview();c.querySelector('#cost-cancel').onclick=()=>{editing=null;c.innerHTML='';};form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('[type=submit]');b.disabled=true;try{await request(`/products/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(values())});editing=null;await load();}catch(err){const box=c.querySelector('#cost-error');box.textContent=err.message;box.hidden=false;b.disabled=false;}};refreshIcons();c.scrollIntoView({behavior:'smooth',block:'nearest'});}
 function orderTable(){const c=root.querySelector('#admin-tab-content');c.innerHTML=`<p class="admin-callout">These are persisted local demo records. Status changes do not contact customers, dispatch a courier or collect COD. Cancelling restores the ordered stock once; cancellation is final.</p>${orders.length?`<div class="table-scroll"><table><thead><tr><th>Reference / date</th><th>Customer</th><th>Cars</th><th>Total</th><th>Status</th><th>Update</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${escape(o.id)}<small>${escape(new Date(o.createdAt).toLocaleString('en-BD'))}</small></td><td>${escape(o.customer.name)}<small>${escape(o.customer.phone)}</small><small>${escape(o.customer.address)}</small><small>${escape(o.customer.zone)}</small></td><td>${o.items.map(i=>`${escape(i.name)} × ${i.quantity}`).join('<br>')}</td><td>${money(o.total)}</td><td><span class="status-pill">${escape(o.status)}</span></td><td>${o.status==='cancelled'?'Final':`<select class="order-status-select" aria-label="New status for ${escape(o.id)}" data-order="${escape(o.id)}">${['placed','confirmed','packed','shipped','delivered','cancelled'].map(s=>`<option ${s===o.status?'selected':''} value="${s}">${s}</option>`).join('')}</select><button data-update-order="${escape(o.id)}">Save</button>`}</td></tr>`).join('')}</tbody></table></div>`:`<h3>No orders in the pit lane yet.</h3><p class="admin-note">Place a local demo order from the storefront to see it here.</p>`}`;
 c.querySelectorAll('[data-update-order]').forEach(b=>b.onclick=async()=>{const id=b.dataset.updateOrder;const select=[...c.querySelectorAll('[data-order]')].find(s=>s.dataset.order===id);if(select.value==='cancelled'&&!confirm('Cancel this demo order and restore its stock? Cancellation is final.'))return;b.disabled=true;try{await request(`/orders/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:select.value})});await load();}catch(err){error(err.message);b.disabled=false;}});}
 login();
}
