import '@fontsource/barlow/400.css';
import '@fontsource/barlow/500.css';
import '@fontsource/barlow/600.css';
import '@fontsource/barlow-condensed/600.css';
import '@fontsource/barlow-condensed/700.css';
import '@fontsource/barlow-condensed/800.css';
import './style.css';
import {createIcons,Heart,ShoppingBag,ArrowUpRight,ArrowRight,ArrowLeft,Plus,Minus,MoveHorizontal,Rotate3d,Banknote,PackageCheck,MapPin,ScanEye,Search,ChevronDown,Info,RotateCcw,X,Trash2,CircleCheck,Copy,Check} from 'lucide';
const icons={Heart,ShoppingBag,ArrowUpRight,ArrowRight,ArrowLeft,Plus,Minus,MoveHorizontal,Rotate3d,Banknote,PackageCheck,MapPin,ScanEye,Search,ChevronDown,Info,RotateCcw,X,Trash2,CircleCheck,Copy,Check};
import {createGarage,createThumbnails,CartDrive} from './cars.js';

const $=(s)=>document.querySelector(s);
const money=v=>new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(v).replace('BDT','৳');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>`<i data-lucide="${name}"></i>`;
function refreshIcons(){createIcons({icons,attrs:{'stroke-width':1.65}});}
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function saveStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
let products=[],thumbnails={},category='All',savedOnly=false,featuredId='skyline',catalog=null;
let cart=readStore('dd:cart:v1',{}),saved=new Set(readStore('dd:saved:v1',[]));
let busy=false,garage,detailGarage,checkoutState=false,lastOrder=null;
const animation=new CartDrive($('#drive-canvas'));
window.__SHOP__={get cart(){return {...cart};},get products(){return products;},animation,get garage(){return garage;},get featuredId(){return featuredId;},get lastOrder(){return lastOrder;},get busy(){return busy;}};
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3400);}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await response.json();}catch{throw new Error('The garage server returned an unreadable response. Try again.');}if(!response.ok)throw new Error(data.error||`Request failed (${response.status}).`);return data;}
function persistCart(){saveStore('dd:cart:v1',cart);updateCount();}
function updateCount(){const count=Object.values(cart).reduce((a,b)=>a+b,0);$('#cart-count').textContent=count;$('#cart-toggle').setAttribute('aria-label',`Open cart, ${count} ${count===1?'car':'cars'}`);$('.saved-dot').hidden=saved.size===0;}
function reconcileCart(){const next={};for(const p of products){const q=Number(cart[p.id]);if(Number.isInteger(q)&&q>0&&p.stock>0)next[p.id]=Math.min(q,p.stock);}cart=next;persistCart();}
function productById(id){return products.find(p=>p.id===id);}
function filtered(){let list=products.filter(p=>(category==='All'||p.category===category)&&(!savedOnly||saved.has(p.id))&&p.name.toLowerCase().includes($('#search').value.trim().toLowerCase()));const sort=$('#sort').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list;}
function renderProducts(){const list=filtered();$('#result-count').textContent=list.length;$('#catalog-status').hidden=!!list.length;$('#catalog-status').innerHTML=list.length?'':`<h3>No cars in this lane.</h3><p>${savedOnly?'Save a casting with its heart button, or browse all cars.':'Try another name or collection.'}</p><button class="button secondary" data-action="clear-filters">Browse all castings</button>`;
 $('#product-grid').innerHTML=list.map(p=>`<article class="product-card" data-product="${escape(p.id)}"><div class="product-image"><span class="series-tag">HOT WHEELS · ${escape(p.series)}</span><button class="save-car ${saved.has(p.id)?'saved':''}" data-action="save" data-id="${escape(p.id)}" aria-label="${saved.has(p.id)?'Unsave':'Save'} ${escape(p.name)}" aria-pressed="${saved.has(p.id)}">${icon('heart')}</button><button class="inspect-image" data-action="detail" data-id="${escape(p.id)}" aria-label="Inspect ${escape(p.name)} in 3D">${thumbnails[p.id]?`<img src="${thumbnails[p.id]}" alt="Illustrative ${escape(p.name)} silhouette in ${escape(p.color)}" width="680" height="410">`:`<span class="image-fallback">${escape(p.name)}<small>3D unavailable on this device</small></span>`}</button><span class="view-hint">${icon('rotate-3d')} Inspect in 3D</span></div><div class="product-info"><span class="product-category">${escape(p.category)} <span>1:64 SCALE</span></span><button class="product-name" data-action="detail" data-id="${escape(p.id)}">${escape(p.name)}</button><div class="product-buy"><div class="price">${money(p.price)}<small>${p.stock>0?'Demo inventory':'Sold out'}</small></div><button class="add-car" data-action="add" data-id="${escape(p.id)}" ${p.stock<=0?'disabled':''} aria-label="Add ${escape(p.name)} to cart">${icon('plus')} <span>Add to garage</span></button></div></div></article>`).join('');refreshIcons();}
function selectFeatured(id){const p=productById(id);if(!p)return;featuredId=id;garage?.setProduct(p);$('#featured-name').textContent=p.name;$('#featured-category').textContent=`${p.category.toUpperCase()} / ${p.series.toUpperCase()}`;$('#hero-add').disabled=p.stock===0;$('#hero-add').dataset.id=id;document.querySelectorAll('[data-featured]').forEach(b=>{b.classList.toggle('active',b.dataset.featured===id);b.setAttribute('aria-pressed',String(b.dataset.featured===id));});}
async function loadCatalog(){catalog=await api('/api/catalog');products=catalog.products;thumbnails=createThumbnails(products);reconcileCart();renderProducts();$('#hero-selector').innerHTML=products.map(p=>`<button data-featured="${escape(p.id)}" style="--swatch:${escape(p.color)}" aria-label="Feature ${escape(p.name)}" aria-pressed="false"><span></span></button>`).join('');if(!garage)garage=createGarage($('#garage-canvas'));selectFeatured(featuredId);if(!garage.ready){$('#garage-canvas').style.display='none';const img=document.createElement('img');img.className='hero-fallback';img.src=thumbnails[featuredId]||'';img.alt='Interactive 3D is unavailable. Browse the garage below.';$('.hero-stage').prepend(img);}}
async function addCar(id,button){const p=productById(id);if(!p)return;if((cart[id]||0)>=p.stock){toast('That is all the demo stock available for this casting.');return;}if(busy){toast('Your car is still arriving. Give it a moment.');return;}
 busy=true;if(button)button.disabled=true;const rect=button?.closest('.product-card,.hero-stage,.product-dialog')?.querySelector('img,canvas')?.getBoundingClientRect()||button?.getBoundingClientRect();const target=$('#cart-toggle').getBoundingClientRect();const src=rect?{x:rect.x+rect.width*.52,y:rect.y+rect.height*.55}:{x:innerWidth*.5,y:innerHeight*.6};$('#drive-caption').textContent=`${p.name} → your garage`;$('#drive-caption').classList.add('visible');
 if($('#product-dialog').open)closeDialog($('#product-dialog'));
 try{await animation.drive(p,src,{x:target.x+target.width/2,y:target.y+target.height/2});cart[id]=(cart[id]||0)+1;persistCart();$('#cart-toggle').classList.remove('arrived');void $('#cart-toggle').offsetWidth;$('#cart-toggle').classList.add('arrived');toast(`${p.name} is in your garage.`);}finally{busy=false;if(button)button.disabled=p.stock===0;$('#drive-caption').classList.remove('visible');}
}
function closeDialog(dialog){dialog?.close();document.body.classList.toggle('dialog-open',!!document.querySelector('dialog[open]'));}
function openDialog(dialog){document.querySelectorAll('dialog[open]').forEach(d=>d.close());dialog.showModal();document.body.classList.add('dialog-open');refreshIcons();}
function cartItems(){return products.filter(p=>cart[p.id]>0).map(p=>({...p,quantity:cart[p.id]}));}
function renderCart(){checkoutState=false;$('#cart-title').textContent='YOUR GARAGE.';const items=cartItems();if(!items.length){$('#cart-body').innerHTML=`<div class="empty-cart">${icon('shopping-bag')}<h3>Your next obsession<br>belongs here.</h3><p>You haven’t parked any cars yet.</p><button class="button primary" data-action="browse">Explore the garage ${icon('arrow-up-right')}</button></div>`;refreshIcons();return;}
 const subtotal=items.reduce((a,p)=>a+p.price*p.quantity,0);$('#cart-body').innerHTML=`<div class="cart-items">${items.map(p=>`<div class="cart-item"><img src="${thumbnails[p.id]||''}" alt="${escape(p.name)}" width="120" height="80"><div><h3>${escape(p.name)}</h3><p>${money(p.price)} <span>· ${escape(p.category)}</span></p><div class="quantity"><button data-action="decrement" data-id="${p.id}" aria-label="Remove one ${escape(p.name)}">${icon('minus')}</button><span>${p.quantity}</span><button data-action="increment" data-id="${p.id}" ${p.quantity>=p.stock?'disabled':''} aria-label="Add one ${escape(p.name)}">${icon('plus')}</button></div></div><button class="icon-btn remove-item" data-action="remove" data-id="${p.id}" aria-label="Remove ${escape(p.name)}">${icon('trash-2')}</button></div>`).join('')}</div><div class="cart-summary"><div><span>Cars subtotal</span><strong>${money(subtotal)}</strong></div><p>Delivery calculated at checkout. Cash on delivery.</p><button class="button primary full" data-action="checkout">Go to checkout ${icon('arrow-right')}</button><span class="demo-caution">Local demo orders only. No money is charged.</span></div>`;refreshIcons();}
function checkout(){if(!cartItems().length)return;checkoutState=true;$('#cart-title').textContent='LAST PIT STOP.';const subtotal=cartItems().reduce((a,p)=>a+p.price*p.quantity,0);const delivery=catalog.delivery||{dhaka:80,outside:150};$('#cart-body').innerHTML=`<form id="checkout-form"><button type="button" class="text-button" data-action="back-cart">${icon('arrow-left')} Back to your garage</button><div class="checkout-notice">${icon('info')} Demo checkout. Your order is saved locally; no payment or real delivery is initiated.</div><label>Your name<input name="name" autocomplete="name" required minlength="2" maxlength="100" placeholder="Full name"></label><label>Bangladesh mobile number<input name="phone" autocomplete="tel" inputmode="tel" required pattern="(?:\\+?88)?01[3-9][0-9]{8}" maxlength="14" placeholder="01XXXXXXXXX"><small>11 digits starting 013–019, or +880 format.</small></label><label>Delivery address<textarea name="address" autocomplete="street-address" required minlength="8" maxlength="500" rows="3" placeholder="House / road, area, city"></textarea></label><fieldset class="delivery-zones"><legend>Delivery zone</legend><label><input type="radio" name="zone" value="dhaka" checked> Inside Dhaka <b>${money(delivery.dhaka)}</b></label><label><input type="radio" name="zone" value="outside"> Outside Dhaka <b>${money(delivery.outside)}</b></label></fieldset><div class="payment-choice">${icon('banknote')} <div>Cash on delivery<small>Demo payment option · no online charge</small></div></div><div class="checkout-totals"><div><span>Cars subtotal</span><b>${money(subtotal)}</b></div><div><span>Delivery</span><b id="delivery-total">${money(delivery.dhaka)}</b></div><div class="order-total"><span>Total</span><b id="checkout-total">${money(subtotal+delivery.dhaka)}</b></div></div><p id="checkout-error" class="form-error" role="alert" hidden></p><button class="button primary full" id="place-order" type="submit">Place demo order ${icon('arrow-right')}</button><p class="checkout-footnote">No card details. No supplier purchase. Final price and stock are verified by the server.</p></form>`;refreshIcons();$('#checkout-form').addEventListener('change',e=>{if(e.target.name==='zone'){const fee=delivery[e.target.value];$('#delivery-total').textContent=money(fee);$('#checkout-total').textContent=money(subtotal+fee);}});$('#checkout-form').addEventListener('submit',submitOrder);}
async function submitOrder(event){event.preventDefault();const form=event.target;if(!form.reportValidity())return;const button=$('#place-order');button.disabled=true;button.textContent='Parking your order…';$('#checkout-error').hidden=true;const fields=Object.fromEntries(new FormData(form));try{
 const result=await api('/api/orders',{method:'POST',body:JSON.stringify({customer:fields,items:cartItems().map(p=>({id:p.id,quantity:p.quantity})),paymentMethod:'cod'})});lastOrder=result.order;cart={};persistCart();products=products.map(p=>({...p,stock:p.stock-(result.order.items.find(i=>i.id===p.id)?.quantity||0)}));renderProducts();showConfirmation(result.order);
 }catch(error){$('#checkout-error').hidden=false;$('#checkout-error').textContent=error.message;button.disabled=false;button.innerHTML=`Place demo order ${icon('arrow-right')}`;refreshIcons();}}
function showConfirmation(order){$('#cart-title').textContent='PARKED & SAVED.';$('#cart-body').innerHTML=`<div class="confirmation">${icon('circle-check')}<h3>Your garage<br>just got bigger.</h3><p>Your <strong>demo order</strong> is saved on this computer. It will not trigger payment or fulfillment.</p><div class="order-reference"><span>ORDER REFERENCE</span><strong>${escape(order.id)}</strong><button class="text-button" data-action="copy-order" data-id="${escape(order.id)}">${icon('copy')} Copy reference</button></div><div class="confirmation-summary"><div><span>Total including delivery</span><b>${money(order.total)}</b></div><div><span>Status</span><b>${escape(order.status)}</b></div></div><p>Keep your reference and phone number to check this order.</p><button class="button primary full" data-action="browse">Back to the garage ${icon('arrow-up-right')}</button></div>`;refreshIcons();}
function showProduct(id){const p=productById(id);if(!p)return;$('#product-detail').innerHTML=`<div class="detail-close-wrap"><button class="icon-btn dialog-close" data-action="close-dialog" aria-label="Close car details">${icon('x')}</button></div><div class="detail-art"><canvas id="detail-canvas" tabindex="0" role="img" aria-label="Interactive illustrative ${escape(p.name)} 3D model"></canvas><button class="text-button detail-rotate" data-action="detail-rotate">${icon('rotate-3d')} Rotate view</button><span>Drag to inspect · illustrative silhouette</span></div><div class="detail-copy"><span class="product-category">${escape(p.category)} / HOT WHEELS</span><h2 id="detail-name">${escape(p.name)}</h2><p class="detail-description">${({skyline:'An unmistakable boxy stance, twin round tail lights and a rear wing. A JDM-inspired silhouette for the collector who notices every detail.',porsche:'A low-slung profile, round headlights and track-focused attitude. Small scale, serious presence.',supra:'A flowing fastback, long hood and sculpted stance. A familiar shape for the JDM shelf.',mustang:'Long hood. Wide stance. Classic muscle. An American-inspired silhouette with racing stripes.',civic:'Compact proportions and a hatchback silhouette. For the garage that knows everyday cars can be icons.',defender:'Upright lines, roof rack and rear-mounted spare. The adventurous side of a die-cast collection.'})[p.id]}</p><dl class="detail-specs"><div><dt>Scale</dt><dd>1:64</dd></div><div><dt>Series</dt><dd>${escape(p.series)}</dd></div><div><dt>Inventory</dt><dd>Demo stock</dd></div><div><dt>Model accuracy</dt><dd>Illustrative</dd></div></dl><div class="detail-price">${money(p.price)}<small>Planning price · based on demo costs</small></div><button class="button primary full" data-action="add" data-id="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Sold out':'Drive it to my garage'} ${icon('shopping-bag')}</button><p class="detail-note">Replace this model with real product photos, exact SKU and card condition before accepting live orders.</p></div>`;openDialog($('#product-dialog'));detailGarage?.dispose?.();detailGarage=createGarage($('#detail-canvas'));detailGarage.setProduct(p);}
function showDemo(){ $('#info-title').textContent='A REAL BUILD. A DEMO GARAGE.';$('#info-content').innerHTML=`<p>This is a working local storefront: 3D inspection, car-to-cart animation, server-side pricing, persistent order records and an owner workbench.</p><h3>What’s illustrative</h3><p>The catalog, quantities, acquisition costs and delivery fees are sample inputs. Procedural 3D silhouettes are not exact Mattel replicas or authenticated product photography.</p><h3>Before you sell</h3><p>Add real stock, verified SKUs, product photographs, accurate supplier costs, actual courier fees, your business identity and a confirmed returns policy. Keep the target price competitive; the margin calculator cannot make an unprofitable supplier price lucrative.</p><h3>About the 30% target</h3><p>The owner calculator includes landed cost, packaging, overhead allocation, returns reserve, shipping subsidy and percentage payment fees. It divides costs by the revenue remaining after fees and a 30% target margin—not a 30% markup. Actual net profit depends on complete, correct costs and realized sales.</p><p>No real payments, supplier purchases or deliveries happen here. No public deployment has been made.</p>`;openDialog($('#info-dialog'));}
function showTracking(){ $('#info-title').textContent='FIND YOUR ORDER.';$('#info-content').innerHTML=`<p>Use the reference and phone number from your demo checkout.</p><form id="tracking-form"><label>Order reference<input name="id" required maxlength="100" placeholder="Your order reference"></label><label>Checkout phone number<input name="phone" required inputmode="tel" maxlength="14" placeholder="01XXXXXXXXX"></label><p id="tracking-error" role="alert" class="form-error" hidden></p><button class="button primary full" type="submit">Check order ${icon('arrow-right')}</button></form><div id="tracking-result"></div>`;openDialog($('#info-dialog'));$('#tracking-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('#tracking-error').hidden=true;$('#tracking-result').innerHTML='';try{const result=await api('/api/orders/lookup',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const o=result.order;$('#tracking-result').innerHTML=`<div class="tracking-card"><h3>${escape(o.id)}</h3><span class="status-pill">${escape(o.status)}</span><ul>${o.items.map(i=>`<li>${escape(i.name)} × ${i.quantity}</li>`).join('')}</ul><p>Total: <strong>${money(o.total)}</strong></p><small>Local demo record. No real fulfillment.</small></div>`;}catch(error){$('#tracking-error').textContent=error.message;$('#tracking-error').hidden=false;}finally{b.disabled=false;}});}

document.addEventListener('click',async e=>{const featured=e.target.closest('[data-featured]');if(featured){selectFeatured(featured.dataset.featured);return;}const categoryButton=e.target.closest('[data-category]');if(categoryButton){category=categoryButton.dataset.category;savedOnly=false;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===categoryButton));renderProducts();return;}const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;
 if(action==='add')await addCar(id,b);
 if(action==='open-cart'){renderCart();openDialog($('#cart-dialog'));}
 if(action==='close-dialog')closeDialog(b.closest('dialog'));
 if(action==='browse'){closeDialog(b.closest('dialog'));$('#garage').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 if(action==='save'){saved.has(id)?saved.delete(id):saved.add(id);saveStore('dd:saved:v1',[...saved]);updateCount();renderProducts();}
 if(action==='wishlist-filter'){savedOnly=!savedOnly;category='All';renderProducts();$('#garage').scrollIntoView({behavior:'smooth'});toast(savedOnly?'Showing your saved castings.':'Showing all castings.');}
 if(action==='clear-filters'){savedOnly=false;category='All';$('#search').value='';$('#sort').value='featured';document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category==='All'));renderProducts();}
 if(action==='detail')showProduct(id);
 if(action==='detail-rotate')detailGarage?.rotate();
 if(action==='increment'){cart[id]=Math.min((cart[id]||0)+1,productById(id).stock);persistCart();renderCart();}
 if(action==='decrement'){if(cart[id]>1)cart[id]--;else delete cart[id];persistCart();renderCart();}
 if(action==='remove'){delete cart[id];persistCart();renderCart();}
 if(action==='checkout')checkout();
 if(action==='back-cart')renderCart();
 if(action==='show-demo')showDemo();
 if(action==='track')showTracking();
 if(action==='copy-order'){try{await navigator.clipboard.writeText(id);toast('Order reference copied.');}catch{toast('Copy the reference shown above.');}}
});
$('#hero-add').addEventListener('click',e=>addCar(featuredId,e.currentTarget));$('#rotate-car').addEventListener('click',()=>garage?.rotate());$('#garage-canvas').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Enter',' '].includes(e.key)){e.preventDefault();garage?.rotate();}});$('#search').addEventListener('input',renderProducts);$('#sort').addEventListener('change',renderProducts);
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('cancel',()=>document.body.classList.remove('dialog-open'));d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d);}});});
refreshIcons();updateCount();
if(location.pathname.startsWith('/admin')){ $('#storefront').hidden=true;$('#admin-app').hidden=false;import('./admin.js').then(m=>m.startAdmin({api,money,escape,refreshIcons})); }else loadCatalog().catch(error=>{ $('#catalog-status').textContent=`${error.message} Refresh the page after starting the local server.`;$('#hero-add').disabled=true;toast('Could not reach the garage server.');});
